feat: snapshot tests during CI (#137)
* feat: make snapshot tests capable of running in parallel.

  This is the default behaviour when running 'cargo test', and it's been slightly annoying to have to run them one by one every time. Now, they happily all run at once by sharing and reusing connections to the on-disk snapshots.

Signed-off-by: KtorZ <matthias.benkort@gmail.com>

* feat: introduce a basic Makefile

Signed-off-by: jeluard <jeluard@users.noreply.github.com>

* feat: make sure snapshot tests are executed during CI

Signed-off-by: jeluard <jeluard@users.noreply.github.com>

* feat: use local cardano-node in CI snapshot tests.

Signed-off-by: KtorZ <matthias.benkort@gmail.com>

* chore: use actions/cache@v4, same as network sync workflow.

Signed-off-by: KtorZ <matthias.benkort@gmail.com>

* fix: make sure the cache path also match for re-use between workflows.

Signed-off-by: KtorZ <matthias.benkort@gmail.com>

* fix: fix cache-hit strategy for cardano-node-db.

  Interstingly enough, a 'cache-hit' value of 'false' does not indicate
  a miss. It indicates a hit on a restore key (and not a _direct_ hit).

  A miss is denoted by an empty string. :|

Signed-off-by: KtorZ <matthias.benkort@gmail.com>

* chore: use same host for Haskell cardano node container.

Signed-off-by: KtorZ <matthias.benkort@gmail.com>

* chore: build Amaru in a separate step

Signed-off-by: KtorZ <matthias.benkort@gmail.com>

* fix: add missing topology config file to Haskell's node configuration.

Signed-off-by: KtorZ <matthias.benkort@gmail.com>

* fix: wrong PID access

Signed-off-by: jeluard <jeluard@users.noreply.github.com>

* fix: fix amaru e2e watch script

Signed-off-by: KtorZ <matthias.benkort@gmail.com>

* chore: update epoch used as stop gap

Signed-off-by: jeluard <jeluard@users.noreply.github.com>

* test

Signed-off-by: jeluard <jeluard@users.noreply.github.com>

* tmp: comment out build part to allow build to finish and cash to be pushed.

Signed-off-by: KtorZ <matthias.benkort@gmail.com>

* chore: only restore cardano-db cache, to save time and avoid weird cache conflict

Signed-off-by: KtorZ <matthias.benkort@gmail.com>

* tmp

Signed-off-by: KtorZ <matthias.benkort@gmail.com>

* fix: fix ledger db snapshots paths + add version key.

Signed-off-by: KtorZ <matthias.benkort@gmail.com>

* remove intermediate log lines.

Signed-off-by: KtorZ <matthias.benkort@gmail.com>

* send INT signal, not TERM, to ensure a clean stop.

Signed-off-by: KtorZ <matthias.benkort@gmail.com>

* .

Signed-off-by: KtorZ <matthias.benkort@gmail.com>

* fix: end sync right after snapshot exit.

Signed-off-by: KtorZ <matthias.benkort@gmail.com>

* split ledge cache restore/save

Signed-off-by: KtorZ <matthias.benkort@gmail.com>

* prune node db.

Signed-off-by: KtorZ <matthias.benkort@gmail.com>

---------

Signed-off-by: KtorZ <matthias.benkort@gmail.com>
Signed-off-by: jeluard <jeluard@users.noreply.github.com>
Co-authored-by: KtorZ <matthias.benkort@gmail.com>

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -97,6 +97,121 @@ jobs:
           fi
         shell: bash
 
+  snapshots:
+    name: Snapshots
+    runs-on: ubuntu-latest
+    if: ${{ !github.event.pull_request.draft }}
+    env:
+      AMARU_PEER_ADDRESS: 127.0.0.1:3001
+    strategy:
+      matrix:
+        network: [ preprod ]
+        cardano_node_version: [ 10.1.4 ]
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Restore cardano-node DB
+        id: cache-cardano-node-db
+        uses: actions/cache/restore@v4
+        with:
+          # The path should match the one used for the 'Nightly Sync' workflow.
+          path: ${{ runner.temp }}/db-${{ matrix.network }}
+          # The key should also match
+          key: cardano-node-ogmios-${{ matrix.network }}
+          restore-keys: |
+            cardano-node-ogmios-${{ matrix.network }}
+
+      - name: Check if cardano-node-db is available
+        if: steps.cache-cardano-node-db.outputs.cache-hit == ''
+        run: |
+          echo "Haskell node db not available, aborting job."
+          exit 1
+
+      - name: Spawn Haskell Node
+        id: spawn-cardano-node
+        shell: bash
+        run: |
+          docker pull ghcr.io/intersectmbo/cardano-node:${{ matrix.cardano_node_version }}
+          make HASKELL_NODE_CONFIG_DIR=cardano-node-config NETWORK=${{ matrix.network }} download-haskell-config
+          docker run -d --name cardano-node \
+            -v ${{ runner.temp }}/db-${{ matrix.network }}:/db \
+            -v ${{ runner.temp }}/ipc:/ipc \
+            -v ./cardano-node-config:/config \
+            -v ./cardano-node-config:/genesis \
+            -p 3001:3001 \
+            ghcr.io/intersectmbo/cardano-node:${{ matrix.cardano_node_version }} run \
+              --config /config/config.json \
+              --database-path /db \
+              --socket-path /ipc/node.socket \
+              --topology /config/topology.json
+
+      - uses: Swatinem/rust-cache@v2
+
+      - name: Build Amaru
+        run: |
+          cargo build --release --locked
+
+      - name: Cache Amaru's ledger.db
+        id: cache-ledger-db
+        uses: actions/cache/restore@v4
+        with:
+          path: ./ledger.db
+          # If the ledger store serialisation format changes and become
+          # incompatible, it is necessary to bump the index below to invalidate
+          # the cached ledger snapshots, and recompute them from the CBOR ones
+          # (i.e. Full bootstrap below)
+          key: ${{ runner.OS }}-ledger-cache-v1
+          restore-keys: |
+            ${{ runner.OS }}-ledger-cache-v1
+
+      - name: Full bootstrap amaru
+        if: steps.cache-ledger-db.outputs.cache-hit != 'true'
+        run: |
+          make bootstrap
+
+      - if: steps.cache-ledger-db.outputs.cache-hit != 'true'
+        uses: actions/cache/save@v4
+        with:
+          path: ./ledger.db
+          key: ${{ runner.OS }}-ledger-cache-v1
+
+      - name: Light bootstrap amaru
+        if: steps.cache-ledger-db.outputs.cache-hit == 'true'
+        run: |
+          make import-headers
+          make import-nonces
+
+      - name: Run node
+        timeout-minutes: 30
+        shell: bash
+        run: |
+          set -eo pipefail
+          # Make sure amaru runs long enough so that snapshot tests can be executed
+          AMARU_TRACE="amaru=debug" cargo run --release -- --with-json-traces daemon --peer-address=$AMARU_PEER_ADDRESS --network=${{ matrix.network }} | while read line; do
+            TARGET_EPOCH=173
+
+            EVENT=$(echo $line | jq -r '.fields.message' 2>/dev/null)
+            SPAN=$(echo $line | jq -r '.spans[0].name' 2>/dev/null)
+
+            if [ "$EVENT" == "exit" ] && [ "$SPAN" == "snapshot" ]; then
+              EPOCH=$(echo $line | jq -r '.spans[0].epoch' 2>/dev/null)
+              if [ "$EPOCH" == "$TARGET_EPOCH" ]; then
+                echo "Target epoch reached, stopping the process."
+                pkill -INT -P $$
+                break
+              fi
+            fi
+          done
+
+      - name: Run tests
+        run: cargo test --release --locked -p amaru -- --ignored
+
+      - name: Teardown haskell node
+        shell: bash
+        run: |
+          docker stop cardano-node
+          docker rm cardano-node
+
   examples:
     name: Examples
     strategy:
