fix: do not trigger GH status checks

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -27,16 +27,22 @@ jobs:
             target: aarch64-apple-darwin
     timeout-minutes: 30
     runs-on: ${{ matrix.environments.runner }}
-    continue-on-error: ${{ matrix.environments.optional || false }}
     steps:
       - uses: actions/checkout@v4
       - uses: Swatinem/rust-cache@v2
-        with:
-          save-if: ${{ github.ref == 'refs/heads/main' }}
       - name: Check format
         run: cargo fmt --all -- --check
       - name: Run clippy
         run: cargo clippy --all-targets --all-features -- -D warnings
       - run: rustup target add ${{ matrix.environments.target }}
       - name: Run tests
-        run: cargo test --locked --all-features --workspace --target ${{ matrix.environments.target }}
+        run: |
+          set +e
+          cargo test --locked --all-features --workspace --target ${{ matrix.environments.target }}
+          exitcode="$?"
+          if [[ "${{ matrix.environments.optional }}" == "true" && "$exitcode" != "0" ]] ; then
+            # Propagate failure as a warning
+            # but do not fail the job
+            echo "::warning::Tests failed with exit code $exitcode"
+            exit 0
+          fi
